apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: uhojfuen3-python
  janus-idp.io/tekton: uhojfuen3-python
  backstage.io/kubernetes-id: uhojfuen3-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: uhojfuen3-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
